# -*- coding: utf-8 -*-
"""HPC-Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xpuVIaHtJHBDp2eOARJi8evmFmP1L8AE
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile Image_Processing_Cuda.cu
# 
#  #include <iostream>
#  #include <stdio.h>
#  #include <cuda.h>
#  #include <time.h>
#  #include <stdlib.h>
#  #include <cmath>
#  #include <opencv2/opencv.hpp>
#  #include <iostream>
# 
# 
# void rbcgray_Sequential(unsigned char *rgb, unsigned char *gray,int height, int width ){
# 
#   for(int row =0; row<  height; row ++  ){
# 
#     for(int col =0; col < width; col++){
#       int index = row* width +col ;
#       int rgbIx = index*3;
# 
#       unsigned char red = rgb[rgbIx +2];
#       unsigned char green = rgb[rgbIx +1] ;
#       unsigned char blue = rgb[rgbIx +0] ;
# 
#       gray[index] = 0.3f *red + 0.6f * green+ 0.1f *blue;
# 
#     }
#   }
# 
#  }
# 
#  __global__ void rbcgray_parallel(unsigned char *rgb, unsigned char *gray,int height, int width ){
# 
#   int col = blockIdx.x * blockDim.x + threadIdx.x;
#   int row = blockIdx.y * blockDim.y + threadIdx.y;
# 
#   if (row < height && col < width){
#     int index = row* width + col;
#     int rgbIx = index*3;
# 
#     float red = (float) rgb[rgbIx +2];
#     float green = (float) rgb[rgbIx +1] ;
#     float blue = (float)rgb[rgbIx +0] ;
# 
#     gray[index] =  (unsigned char) (0.3f *red + 0.6f * green+ 0.1f *blue);
# 
# 
# 
#   }
#  }
# 
# void flipHorizontalSequential(unsigned char *input, unsigned char *output, int height, int width, int channel){
#   for(int row = 0; row < height; row ++){
#     for(int col= 0; col < width; col++){
#       for(int c =0; c < channel; c++){
#         int id_in= row * width *channel + col *channel + c;
#         int id_out = row * width * channel + (width -1 - col) * channel + c;
#         output[id_out]= input[id_in];
#       }
#     }
#   }
# }
# 
# __global__ void flipHorizontalParallel(unsigned char *input, unsigned char *output, int height, int width, int channel){
#   int col = blockIdx.x * blockDim.x + threadIdx.x;
#   int row =  blockIdx.y * blockDim.y + threadIdx.y;
#   if(row < height && col < width){
#     for(int c =0; c< channel; c++){
#       int id_in= row * width *channel + col *channel + c;
#       int id_out = row * width * channel + (width -1 - col) * channel + c;
#       output[id_out]= input[id_in];
# 
#     }
#   }
# }
# 
# void blurSequential(unsigned char *input, unsigned char *output, int height, int width, int size ){
# 
#   int radious = size/2;
#   for(int row =0; row < height; row++){
#     for(int col =0; col < width; col++){
#     int sum =0;
#     int count =0;
#     for(int i = -radious; i <= radious; i++){
#       for(int y = -radious; y <= radious; y++){
#         int xx = col + y;
#         int yy = row + i;
# 
#         if(yy >= 0 && yy < height && xx >=0 && xx < width){
#           sum += input[yy * width + xx];
#           count ++;
#         }
#       }
#     }
#     output[row * width + col] = sum/count;
#   }
# }
# }
# 
# __global__  void blurParalell(unsigned char *input, unsigned char *output, int height, int width, int size){
#   int col = blockIdx.x * blockDim.x + threadIdx.x;
#   int row =  blockIdx.y * blockDim.y + threadIdx.y;
#   int radious = size/2;
# 
#   if(row < height && col < width){
#     int sum = 0, count =0;
#     for(int i = -radious; i <= radious; i++){
#       for(int y = -radious; y <= radious; y++){
#         int xx = col + y;
#         int yy = row + i;
# 
#         if(yy >= 0 && yy < height && xx >=0 && xx < width){
#           sum += input[yy * width + xx];
#           count ++;
#         }
#       }
#     }
#     output[row * width + col] = sum/count;
#   }
# }
# 
# int main(){
# 
#   cv:: Mat img = cv:: imread("rgbImage.jpg", cv:: IMREAD_COLOR);
#   if(img.empty()){
#     printf("Error loading Image");
#   }
# 
#   int width = img.cols;
#   int height = img.rows;
# 
#   cv :: Mat gray_cpu(height, width, CV_8UC1);
#   cv :: Mat gray_gpu(height, width, CV_8UC1);
# 
# 
#   cv :: Mat flip_cpu(height, width,CV_8UC1);
#   cv :: Mat flip_gpu(height, width,CV_8UC1);
# 
#   cv :: Mat blur_cpu(height, width,CV_8UC1);
#   cv :: Mat blur_gpu(height, width,CV_8UC1);
# 
#   clock_t start = clock();
#   rbcgray_Sequential(img.data, gray_cpu.data, height, width);
#   clock_t end = clock();
# 
#   double SequentialTime = 1000 *(end- start)/CLOCKS_PER_SEC;
# 
# 
#   unsigned char *rgbs, *grays, *d_flip, *d_blur;
# 
#   size_t rgb = width*height *3 *sizeof(unsigned char);
#   size_t gray = width *height * sizeof(unsigned char);
# 
#   cudaMalloc(&rgbs, rgb);
#   cudaMalloc(&grays, gray);
#   cudaMalloc(&d_flip, gray);
#   cudaMalloc(&d_blur, gray);
# 
#   cudaMemcpy(rgbs, img.data, rgb, cudaMemcpyHostToDevice);
# 
#   float myTime;
#   cudaEvent_t myTimerStart, myTimerStop;
# 
#   cudaEventCreate(&myTimerStart);
#   cudaEventCreate(&myTimerStop);
# 
#   dim3 block(16,16);
#   dim3 grid((width + block.x -1)/block.x, (height+ block.y -1)/block.y);
# 
#   cudaEventRecord(myTimerStart, 0);
# 
#   rbcgray_parallel<<<grid, block>>>(rgbs, grays, height, width);
#   cudaError_t err = cudaGetLastError();
#   if (err != cudaSuccess) {
#     printf("CUDA kernel launch error: %s\n", cudaGetErrorString(err));
#     }
# 
#   cudaEventRecord(myTimerStop, 0);
#   cudaEventSynchronize(myTimerStop);
# 
#   cudaEventElapsedTime(&myTime, myTimerStart, myTimerStop);
# 
#   cudaMemcpy(gray_gpu.data, grays, gray, cudaMemcpyDeviceToHost);
# 
#   cv::imwrite("original.png", img);
#   cv::imwrite("gray_cpu.png", gray_cpu);
#   cv::imwrite("gray_gpu.png", gray_gpu);
# 
# 
#   printf("Performance comparison for Grayscale conversion: ");
#   printf("\n");
#   printf("Sequential time: %.3f ms\n", SequentialTime );
#   printf("Parallel time: %.3f ms\n", myTime);
# 
#   if(SequentialTime > myTime){
#     printf("The Paralell Implementation was faster by %.3f ms ", SequentialTime - myTime);
#   }
# 
#   else if(myTime > SequentialTime){
#     printf("The sequential Impementation was faster by %.3f ms", myTime -SequentialTime);
# 
# 
#   }
#   int performanceImprovement = ((SequentialTime- myTime)/SequentialTime) *100;
#   printf(performanceImprovement);
# 
# 
#   float speedupGrayscale = SequentialTime/myTime;
# 
#   printf("\n The paralell implementation is about %.3f xfaster, than the sequential implementation.", speedupGrayscale);
#   printf("\n");
# 
#   clock_t startFlip = clock();
#   flipHorizontalSequential(gray_cpu.data, flip_cpu.data, height, width,1);
#   clock_t endFlip = clock();
#   double flipseqTime = 1000 *(endFlip-startFlip)/CLOCKS_PER_SEC;
# 
#   cudaEventRecord(myTimerStart);
#   flipHorizontalParallel<<<grid, block>>>(grays, d_flip, height, width,1);
#   cudaEventRecord(myTimerStop);
#   cudaEventSynchronize(myTimerStop);
#   cudaEventElapsedTime(&myTime, myTimerStart, myTimerStop);
#   cudaMemcpy(flip_gpu.data, d_flip, gray, cudaMemcpyDeviceToHost);
# 
#   cv::imwrite("flip_seq.png", flip_cpu);
#   cv::imwrite("flip_parallel.png", flip_gpu);
# 
#   printf("\n");
#   printf("Performance comparison for the Image flip: ");
#   printf("\n");
#   printf("Sequential time: %.3f ms\n", flipseqTime );
#   printf("Parallel time: %.3f ms\n", myTime);
#   float speedupfip = flipseqTime/myTime;
# 
#   printf("\n The paralell implementation is about %.3f xfaster, than the sequential implementation.", speedupfip);
# 
#   int size =5;
#   clock_t startBlur = clock();
#   blurSequential(gray_cpu.data, blur_cpu.data, height,width, size);
#   clock_t endBlur = clock();
# 
#   double blurSeqTime = 1000* (endBlur-startBlur)/CLOCKS_PER_SEC;
# 
#   cudaEventRecord(myTimerStart);
#   blurParalell<<<grid,block>>> (grays, d_blur, height, width, size);
# 
#   cudaEventRecord(myTimerStop);
#   cudaEventSynchronize(myTimerStop);
#   cudaEventElapsedTime(&myTime, myTimerStart, myTimerStop);
#   cudaMemcpy(blur_gpu.data, d_blur,gray, cudaMemcpyDeviceToHost);
# 
#   cv :: imwrite("blur_sequential.png", blur_cpu);
#   cv :: imwrite("blur_parallel.png", blur_gpu);
#   printf("\n");
#   printf("Performance comparison for the Image Blur: ");
#   printf("\n");
#   printf("Sequential time: %.3f ms\n", blurSeqTime );
#   printf("Parallel time: %.3f ms\n", myTime);
#   float speedupBlur = blurSeqTime/myTime;
# 
#   printf("\n The paralell implementation is about %.3f xfaster, than the sequential implementation.", speedupBlur);
# 
# 
# 
# 
#   cudaEventDestroy(myTimerStart);
#   cudaEventDestroy(myTimerStop);
#   cudaFree(grays);
#   cudaFree(rgbs);
#   cudaFree(d_flip);
#   cudaFree(d_blur);
# 
#   return 0;
# }

!ls



!nvcc Image_Processing_Cuda.cu -o Image_Processing_Cuda \
    -gencode arch=compute_75,code=sm_75 `pkg-config --cflags --libs opencv4`

!apt-get update
!apt-get install -y libopencv-dev

from google.colab import files
files.upload()

!./Image_Processing_Cuda

!nvcc --version
!nvidia-smi

!ls -l Image_Processing_Cuda.cu

from google.colab.patches import cv2_imshow
import cv2

o = cv2.imread("original.png")

cpu= cv2.imread("gray_cpu.png")

gpu= cv2.imread("gray_gpu.png")

blurcpu = cv2.imread("blur_sequential.png");

blurgpu = cv2.imread("blur_parallel.png");

flipcpu=cv2.imread("flip_seq.png") ;
flipgpu=cv2.imread("flip_parallel.png");


print("Original image")
cv2_imshow(o)

print("Sequential Image using Grayscale conversion" )
cv2_imshow(cpu)
print("Parallel image using grayscale Conversion")
cv2_imshow(gpu)


print("Blur Sequential Implementation");
cv2_imshow(blurcpu);

print("Blur Parallel Implementation");
cv2_imshow(blurgpu);


print("Flip Sequential Implementation");
cv2_imshow(flipcpu);

print("Flip Parallel Implementation");
cv2_imshow(flipgpu);